### ISSUE TITLE
Support Cors headers 

### ISSUE THREAD

**Issue by Dogfalo** [pylotcode/aiohttp-tus#4]
There doesn't seem to be any way currently to add CORS headers

I tried doing this with `aiohttp-cors` and received an error like this:
```
<PlainResource 'tus_upload_L3VwbG9hZHM_'  /uploads> already has OPTIONS handler <function upload_options at 0x7fa21b527670>
```

**Comment by playpauseandstop** [comment]
Hi @Dogfalo,

Yes, there is a known issue with `aiohttp-cors`, that it doesn’t allow to provide CORS headers for OPTIONS requests cause of the error you mentioned, as it tries to setup a handler for OPTIONS request, but is is already taken

I suggest you to give a try of [aiohttp-middlewares](https://aiohttp-middlewares.readthedocs.io) and its `cors_middleware` as it allows to provide CORS headers even for OPTIONS requests

Hope it will work out for you

——

To make it more obvious, I’ll update the documentation with tutorial on how to provide CORS headers for `aiohttp-tus` library

**Comment by Dogfalo** [comment]
Thanks for the reply! I am just trying to understand, what makes the aiohttp-middleware different? Does it just add headers into the handler without trying to create a new handler?

**Comment by playpauseandstop** [comment]
The high-level details described [in aiohttp-middlewares docs](https://aiohttp-middlewares.readthedocs.io/en/latest/usage.html#cors-middleware), but if you need more technical details, here they go.

1. `aiohttp-cors` [registers](https://github.com/aio-libs/aiohttp-cors/blob/73510a3a9212afd1d3740fd8b2feba63a1dcfe13/aiohttp_cors/urldispatcher_router_adapter.py#L173) `OPTIONS` handler to deal with CORS preflight requests, this resulted in two issues:
   - Inability to use `aiohttp-cors`  with other `OPTIONS` handlers
   - Inability to use `aiohttp-cors` with wildcard `*` handlers, https://github.com/aio-libs/aiohttp-cors/issues/241
2. While `cors_middleware` is a regular [middleware](https://docs.aiohttp.org/en/stable/web_advanced.html#middlewares), which does not register any handlers for dealing with preflight requests. It checks, [whether](https://github.com/playpauseandstop/aiohttp-middlewares/blob/master/aiohttp_middlewares/cors.py#L207) current request is a CORS preflight and if so, does not call handler, but [provide an empty response](https://github.com/playpauseandstop/aiohttp-middlewares/blob/master/aiohttp_middlewares/cors.py#L229) to satisfy CORS needs.

This difference allows `cors_middleware` to fix both of `aiohttp-cors` issues as well as simplify dealing with CORS headers for `aiohttp.web` applications at all, as their setup looks like,

```py
from aiohttp import web
from aiohttp_middlewares import cors_middleware

# Allow CORS requests from URL http://localhost:3000
app = web.Application(
    middlewares=[
        cors_middleware(origins=["http://localhost:3000"])
    ]
)
```

[More examples](https://aiohttp-middlewares.readthedocs.io/en/latest/usage.html#id1) available in `cors_middleware` docs.

Hope this makes sense for you.

**Comment by Dogfalo** [comment]
Makes sense, thanks for the explanation!

**Comment by playpauseandstop** [comment]
Docs updated: https://aiohttp-tus.readthedocs.io/en/latest/usage.html#cors-headers
